# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "./"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Japan"

  - package-ecosystem: "github-actions"
    directory: "./.github/workflows"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Japan"
