schema = 3

[mod]
  [mod."ariga.io/atlas"]
    version = "v0.14.2"
    hash = "sha256-a6YbONYI5nJVTRyAoD8xGBnkmN3ktF7DpsYfMmk8mfM="
  [mod."github.com/agext/levenshtein"]
    version = "v1.2.1"
    hash = "sha256-SuFgpvp7KGO4f2t0KnkhSUv7iRI7oGq40CjRc1tLNr4="
  [mod."github.com/apparentlymart/go-textseg/v15"]
    version = "v15.0.0"
    hash = "sha256-960kVVQSGhx1Gww5cfoNeM3yXaA4dwlv+AFhKh6EGlA="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/go-openapi/inflect"]
    version = "v0.19.0"
    hash = "sha256-jS969dMoR2zLfVfsIQoQIbATyE5p2mIZfW9SnxY7W68="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.6"
    hash = "sha256-OlzzRmcIdX45NA5h/C90NfJ/th0LB+tMHT6WzdQFK1M="
  [mod."github.com/hashicorp/hcl/v2"]
    version = "v2.20.0"
    hash = "sha256-SXGawRaK0HrnZURmhh8jds3xNOy3I5f97yThbeL41BU="
  [mod."github.com/mitchellh/go-wordwrap"]
    version = "v0.0.0-20150314170334-ad45545899c7"
    hash = "sha256-aR+xW4TnVo96Cbw168fhdIBEh7O43mOlHdLx/WxrwVs="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/stretchr/testify"]
    version = "v1.9.0"
    hash = "sha256-uUp/On+1nK+lARkTVtb5RxlW15zxtw2kaAFuIASA+J0="
  [mod."github.com/zclconf/go-cty"]
    version = "v1.14.3"
    hash = "sha256-v5eTB5/lweAxQPYffQ5qy3ds5J6PzdXYWEoV6n8VplY="
  [mod."golang.org/x/mod"]
    version = "v0.16.0"
    hash = "sha256-aN1Cz5Wqd9YCjK8nFW6JWn+n1HfFoEcgYZmGO/FYtbw="
  [mod."golang.org/x/text"]
    version = "v0.11.0"
    hash = "sha256-W/XvTPAGIOlFVwZ7rTaEid7pdRtb4wc6a+nyOW99/ks="
  [mod."golang.org/x/tools"]
    version = "v0.19.0"
    hash = "sha256-Xf05Ao398gBzxn5C8H6x+XsLjFLIm+UUfpDekQYA0cw="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
