name: CI

on:
  push:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1

      - name: Setup Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.sum
          cache: true

      - name: Build
        run: go build

      - name: Test
        run: go test ./...
